# Generated by Django 4.1.7 on 2023-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='number',
            new_name='phone',
        ),
    ]
