# Generated by Django 4.1.7 on 2023-04-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_rename_number_response_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='response',
            new_name='responseForm',
        ),
    ]
