# Generated by Django 4.1.7 on 2023-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_rename_response_responseform'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseform',
            name='docs',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='docs/'),
        ),
    ]
