# Generated by Django 4.1.7 on 2023-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_responseform_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseform',
            name='docs',
        ),
    ]
